### ISSUE TITLE
got this issue, node stopped

### ISSUE THREAD

**Issue by alterkahn** [mvs-org/hyperspace#1]
Version: 0.0.4-0f235c7-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/std/src/panicking.rs:581:17
   2: std::panicking::begin_panic::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: std::panicking::begin_panic
   5: primitive_types::U256::div_mod
   6: betelgeuse_pow::mine
   7: betelgeuse::service::new_full::{{closure}}
   8: std::sys_common::backtrace::__rust_begin_short_backtrace
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/alloc/src/boxed.rs:1042:9
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/alloc/src/boxed.rs:1042:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/std/src/sys/unix/thread.rs:87:17
  11: start_thread
  12: __clone

Thread '<unnamed>' panicked at 'division by zero', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/primitive-types-0.7.3/src/lib.rs:38

**Comment by alterkahn** [comment]
node identity is: 12D3KooWSKn56khKrCjYrkhbuvBfbpDRZAYEeA7bKTqEN243Z2He

**Comment by OIEIEIO** [comment]
alphatestnet randX POW minerbug. All gone update to latest node software. Close issue pls.
