### ISSUE TITLE
node stopped on the block shown below and didn't work until it has been relaunched

### ISSUE THREAD

**Issue by alterkahn** [mvs-org/hyperspace#2]
![80f28d143938d76ebf6edcfdc003e2fa.png](https://picua.org/images/2021/02/03/80f28d143938d76ebf6edcfdc003e2fa.png)

**Comment by alterkahn** [comment]
Local node identity is: 12D3KooWSKn56khKrCjYrkhbuvBfbpDRZAYEeA7bKTqEN243Z2He

**Comment by OIEIEIO** [comment]
alphatestnet randX POW minerbug. All gone update to latest node software. Close issue pls.
